import "./globals.css";
import MainHeader from "@/components/main-header/main-header";

export const metadata = {
  title: "Mortgage Renewals",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://use.typekit.net/uzv7jan.css"
        ></link>
      </head>
      <body>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
