import "./globals.css";
import Script from "next/script";

import MainHeader from "@/components/main-header/main-header";

export const metadata = {
  title: "Mortgage Renewals",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://use.typekit.net/uzv7jan.css"
        ></link>
        <Script
          id="gmaps"
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_KEY}&libraries=places&loading=async&v=weekly`}
          strategy="afterInteractive"
        />
      </head>
      <body>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
